apiVersion: v1
kind: Service
metadata:
  name: sftp-nodeport
  namespace: sftp
spec:
  selector:
    app: sftp-server
  ports:
  - name: sftp
    port: 22
    nodePort: 30022
    protocol: TCP
  type: NodePort