apiVersion: v1
kind: Service
metadata:
  name: sftp-service
  namespace: sftp
spec:
  selector:
    app: sftp-server
  ports:
  - name: sftp
    port: 22
    targetPort: 22
    protocol: TCP
  type: ClusterIP